# Generated by Django 2.2.7 on 2019-11-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ufile',
            name='fileloc',
            field=models.FileField(null=True, upload_to='User_files/', verbose_name=''),
        ),
    ]
